import { type PublicEnv, validatePublicEnv } from "./env-core";

export const publicEnv: PublicEnv = validatePublicEnv({
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
  NEXT_PUBLIC_BOOK_CALL_LINK: process.env.NEXT_PUBLIC_BOOK_CALL_LINK,
  NEXT_PUBLIC_IOS_PUBLISHING_GUIDE_URL:
    process.env.NEXT_PUBLIC_IOS_PUBLISHING_GUIDE_URL,
  NEXT_PUBLIC_ANDROID_PUBLISHING_GUIDE_URL:
    process.env.NEXT_PUBLIC_ANDROID_PUBLISHING_GUIDE_URL,
  NEXT_PUBLIC_STRIPE_NEXTNATIVE_STARTER_PRICE_ID:
    process.env.NEXT_PUBLIC_STRIPE_NEXTNATIVE_STARTER_PRICE_ID,
  NEXT_PUBLIC_STRIPE_NEXTNATIVE_ALL_IN_PRICE_ID:
    process.env.NEXT_PUBLIC_STRIPE_NEXTNATIVE_ALL_IN_PRICE_ID,
  NEXT_PUBLIC_STRIPE_NEXTNATIVE_STARTER_PRODUCT_ID:
    process.env.NEXT_PUBLIC_STRIPE_NEXTNATIVE_STARTER_PRODUCT_ID,
  NEXT_PUBLIC_STRIPE_NEXTNATIVE_ALL_IN_PRODUCT_ID:
    process.env.NEXT_PUBLIC_STRIPE_NEXTNATIVE_ALL_IN_PRODUCT_ID,
  NEXT_PUBLIC_STRIPE_NEXTNATIVE_PROMOTION_CODE_ID:
    process.env.NEXT_PUBLIC_STRIPE_NEXTNATIVE_PROMOTION_CODE_ID,
});
